title: Georgia Harbor-Collins
description: Mathematics Ph.D. Student
site_title: hi

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
email: georgia.harbor-colins@uconn.edu

# absolute or relative
profile_picture: assets/images/profile.png

# Google Analytics ID
google_analytics: 